### ISSUE TITLE
ExpectedObject.ShouldMatch does not support parallel tests

### ISSUE THREAD

**Issue by RomanDidenko** [derekgreer/expectedObjects#12]
In tests that run in paralllel ExpectedObject.ShouldMatch throws different exceptions as mutiple threads write to IWriter stored in static WriterContext.Stack field that is not thread safe.

Most probably WriterContext.Stack can be marked with ThreadStatic attrbite to solve the problem but async tests will still not be supported. AsyncLocal (.net 4.6+) may be used to solve the problem.

Do you consider parallel test support implementation?

**Comment by derekgreer** [comment]
I'll get it taken care of.

**Comment by derekgreer** [comment]
Fixed in version [2.3.0](https://www.nuget.org/packages/ExpectedObjects/2.3.0)
