### ISSUE TITLE
Null reference exception when called ShouldMatch

### ISSUE THREAD

**Issue by RomanDidenko** [derekgreer/expectedObjects#13]
public class when_comaring_objects_with_array_properties_that_have_null_items_and_do_not_match
    {
        static object _actual;
        static bool _result;
        static object _expected;

        Establish context = () =>
        {
            _expected = new { Array = new[] { "1", null } };
            _actual = new { Array = new string[] { null, null } };
        };

        Because of = () =>
        {
            _expected.ToExpectedObject().ShouldMatch(_actual);
            _result = true;
        };

        It should_be_equal = () => _result.ShouldBeTrue();
    }

**Comment by derekgreer** [comment]
Fixed in version [2.3.1](https://www.nuget.org/packages/ExpectedObjects/2.3.1)
