### ISSUE TITLE
StackOverflowException on ShouldMatch method call on objects with recursion

### ISSUE THREAD

**Issue by RomanDidenko** [derekgreer/expectedObjects#14]
public class when_comaring__different_objects_with_array_properties_with_items_that_have_back_reference_to_parent_object
    {
        static object _actual;
        static bool _result;
        static object _expected;

        Establish context = () =>
        {
            var expected = new { Array = new object[1] };
            expected.Array[0] = new { Parent = expected, Id = 1 };

            _expected = expected;

            var actual = new { Array = new object[1] };
            actual.Array[0] = new { Parent = actual, Id = 2 };

            _actual = actual;
        };

        Because of = () =>
        {
            _expected.ToExpectedObject().ShouldMatch(_actual);
            _result = true;
        };

        It should_be_equal = () => _result.ShouldBeTrue();
    }

**Comment by derekgreer** [comment]
Fixed in version [2.3.1](https://www.nuget.org/packages/ExpectedObjects/2.3.1)
