### ISSUE TITLE
Ignoring multiple members

### ISSUE THREAD

**Issue by Mardoxx** [derekgreer/expectedObjects#17]
How do you ignore multiple members, do we have to do this?

```cs
ToExpectedObject(config => {
    config.Ignore(...);
    config.Ignore(...);
})
```

Would it be possible to make [`Ignore`](https://github.com/derekgreer/expectedObjects/blob/0dd34b9433ac2038b7fd70b9d27d10d70c84849e/src/ExpectedObjects/ConfigurationContextExtensions.cs#L51) return `IConfigurationContext<T>` instead to allow chaining?

**Comment by GabrielBBF** [comment]
@derekgreer Any update on this? I sincerely need the requirement to be able to ignore more than one member within my test configuration.

**Comment by master-toma** [comment]
Hi, I miss this feature as well. Do you have any workaround how to ignore more then 1 member?

**Comment by silkfire** [comment]
@master-toma As per Mardoxx' comment, that's the only way to do it today.

The argument is an `Action<>`, so you can expand it and specify members to ignore, one per line

**Comment by derekgreer** [comment]
I’ll try to address this soon.

**Comment by derekgreer** [comment]
Enabled in version 3.1.0.
