### ISSUE TITLE
Ignore fileds in contained lists

### ISSUE THREAD

**Issue by xplicit** [derekgreer/expectedObjects#24]
I have a class

    public class Application
    {
          public int Id { get; set;}
          public List<Localization> Localizations {get;set;}
    }

    public class Localization
    {
         public int Id {get; set;}
         public string Data { get; set; }
    }

I want to compare Application by ignoring all `Id` fields (ignoring `Localization.Id` also). But when I write

      var expected = testApp.ToExpectedObject(ctx => ctx.Ignore(x => x.Localization[0].Id));

It transforms ignored member to `Application.Id` and throws exception when Localization.Id differs from expected Localization.Id. How this comparison could be made?

**Comment by derekgreer** [comment]
As the syntax ```testApp.ToExpectedObject(ctx => ctx.Ignore(x => x.Localization[0].Id))``` would suggest an expression to ignore only the specific member named Id on element 0 of the Localization list (which is now supported), I facilitated the desired behavior by adding the ability to specify a relative or absolute string path to the members to be ignored, so ```ctx.Ignore("Id")``` will now ignore all members named Id within the entire actual object graph.
