### ISSUE TITLE
Considere inherited fields

### ISSUE THREAD

**Issue by tiago-aguiar-moreira** [derekgreer/expectedObjects#25]
I have a basic class, and i inherit in another class.

```
    public class Credential : CredentialBase
    {
        public DatabaseSQL DatabaseSQL { get; }
    }

    public class CredentialBase
    {
        protected string Host { get; set; }
        protected string User { get; set; }
        protected string Password { get; set; }
        protected string DatabaseName { get; set; }
    }
```

But when i compare, the fields in inherited class is not found.

```
        public void ShouldCreateCredential()
        {
            var expectedCredential = new
            {
                Host = _host,
                User = _user,
                Password = _password,
                DatabaseName = _databaseName,
                DatabaseSQL = _databaseSQL
            };

            var credential = new Credential(
                expectedCredential.Host,
                expectedCredential.User,
                expectedCredential.Password,
                expectedCredential.DatabaseName,
                expectedCredential.DatabaseSQL);

            expectedCredential.ToExpectedObject().ShouldMatch(credential);
        }
```

The compare only works if the set fields like public from inherited class.

**Comment by derekgreer** [comment]
This request isn't really for ExpectedObjects to consider inherited fields, but to enable it to consider internal state as part of it's test for equality.   I would be interested in hearing arguments for this behavior, but a present I believe the fundamental question of "_Does this thing have the same value as this other thing?_", or "_Does this thing approximate the same value as this other thing?_", only makes sense when viewed from the perspective of the value they are intended to present to the world.  If two response objects have 10 public properties all with the same values, the fact that they arrive at those same values in different ways (use of protected or private fields, etc.) shouldn't be of concern to the recipient of the response.
