### ISSUE TITLE
Stackoverflow exception if you have DateTimeOffset property.

### ISSUE THREAD

**Issue by Atomosk** [derekgreer/expectedObjects#26]
It's hard to reproduce, since it requires static property Now to change its value between calls. Everything works fine on DateTimeOffset itself, but on some objects it fails with stack looking like that

ObjectStringExtensions.CreateObject() at ObjectStringExtensions.cs:line 61 [28]
ObjectStringExtensions.GetCSharpString() at ObjectStringExtensions.cs:line 98 [28]
ObjectStringExtensions.CreateObject() at ObjectStringExtensions.cs:line 61 [27]
ObjectStringExtensions.GetCSharpString() at ObjectStringExtensions.cs:line 98 [27]
ObjectStringExtensions.CreateObject() at ObjectStringExtensions.cs:line 61 [26]
ObjectStringExtensions.GetCSharpString() at ObjectStringExtensions.cs:line 98 [26]
ObjectStringExtensions.CreateObject() at ObjectStringExtensions.cs:line 61 [25]
ObjectStringExtensions.GetCSharpString() at ObjectStringExtensions.cs:line 98 [25]
ObjectStringExtensions.CreateObject() at ObjectStringExtensions.cs:line 61 [24]

So I think it is possible to reproduce with code
```
var now = DateTimeOffset.Now;
now.ToExpectedObject().ShouldEqual(now);
```
if you add Thread.Sleep somewhere in GetCSharpString. I wonder why does CreateObject check for static properties anyway.

**Comment by nsarris** [comment]
I commited a PR, it was an issue with the reporting serializer which handled DateTime but not DateTimeOffset

**Comment by derekgreer** [comment]
PR merged.
