### ISSUE TITLE
From version 3.3.1 nullable properties can no longer be ignored

### ISSUE THREAD

**Issue by SimonAndrews** [derekgreer/expectedObjects#37]
**Issue**

From version 3.3.1 nullable properties on a class that were previously ignored now fail in tests.

**Example Code**

`    public class Program
    {
        static void Main(string[] args)
        {
			var testObject = new TestObject
            {
                TestInt = 12345,
                TestString = "Test String",
                TestDateTime = DateTime.Now.Date,
                TestNullDateTime = DateTime.Now
            };

            var expectedObject = new TestObject
            {
                TestInt = 12345,
                TestString = "Test String",
                TestDateTime = DateTime.Now.Date
            }.ToExpectedObject(x => x.Ignore(i => i.TestNullDateTime));

            expectedObject.ShouldEqual(testObject);
		}
    }

    public class TestObject
    {
        public int TestInt { get; set; }
        public string TestString { get; set; }
        public DateTime TestDateTime { get; set; }
        public DateTime? TestNullDateTime { get; set; }
    }`

**Result**
![image](https://user-images.githubusercontent.com/6128975/104298075-7b594e80-54bb-11eb-97b9-13fb74e7e077.png)

**Expected Result**
After upgrading to the latest version nullable types should still be able to be ignored.

I've also tried the newer methods IgnoreAbsolutePath and IgnoreRelativePath with the same results

**Comment by derekgreer** [comment]
Fixed in version 3.4.1.
