### ISSUE TITLE
Expected Explicit Type with modified checks on properties

### ISSUE THREAD

**Issue by RhysC** [derekgreer/expectedObjects#5]
Hi Derek.
Here is what I kinda would like

``` csharp
var expected = new MyCommand {
PayloadA = "something specific",
PropertyB = 123456
}
.ToExpectedObject()
.WithNonDefaults( c => c.MessageId); //i.e. special handling of this property - could be generic .With<T> where T is IComparison
```

I.E. our message ID is a GUID which is assigned in the code but not known upfront, we _need_ to make sure it is assigned. 
### Using named types (ie not anon types):

Currently the match fails as the expected object has the GUID as empty (ie the default value). 
### Using an anon object

We can get the match to pass as we can say something like :

``` csharp
var expected = new {
MessageId = NotDefault<Guid>(),
PayloadA = "something specific",
PropertyB = 123456
}
```

However this means we can not ensure the correct type is passed (command handlers  are invoked based on message type ie `Handle<T>` ) 
The issue here is we have several commands that have similar structure, differing only by type - when ordering of those messages is important we can't use ExpectedObjects to fully assert correctness.

Hoping there is something out of the box that can help us here - thanks for your time on this

Rhys

**Comment by derekgreer** [comment]
This can now be achieved in v2.2.0 using ToExpectedObject(ctx => ctx.Member(x => x.SomeProperty).UsesComparison(/* supply a custom IComparison */))
